# utils/config.py
# Конфигурация проекта

# Тексты для анализа
TEXTS_FOR_ANALYSIS = [
    "Hello world! This is a test text in English.",
    "Привет, мир! Это тестовый текст на русском языке.",
    "Bonjour le monde! Ceci est un texte de test en français.",
    "Hola mundo! Este es un texto de prueba en español.",
    "Hallo Welt! Dies ist ein deutscher Testtext.",
    "你好，世界！这是中文测试文本。",
    "こんにちは世界！これは日本語のテストテキストです。"
]

# Названия языков по кодам
LANGUAGE_NAMES = {
    'en': 'English',
    'ru': 'Russian',
    'fr': 'French',
    'es': 'Spanish',
    'de': 'German',
    'it': 'Italian',
    'pt': 'Portuguese',
    'zh-cn': 'Chinese',
    'zh': 'Chinese',
    'ja': 'Japanese',
    'ko': 'Korean',
    'ar': 'Arabic',
    'hi': 'Hindi',
    'tr': 'Turkish',
    'el': 'Greek',
    'pl': 'Polish',
    'uk': 'Ukrainian',
    'kk': 'Kazakh',
    'nl': 'Dutch',
    'sv': 'Swedish',
    'fi': 'Finnish',
    'hu': 'Hungarian',
    'cs': 'Czech',
    'ro': 'Romanian',
    'bg': 'Bulgarian',
    'sr': 'Serbian',
    'mk': 'Macedonian',
    'hr': 'Croatian',
    'sl': 'Slovenian',
    'sk': 'Slovak',
    'da': 'Danish',
    'no': 'Norwegian',
    'is': 'Icelandic',
    'lv': 'Latvian',
    'lt': 'Lithuanian',
    'et': 'Estonian',
    'he': 'Hebrew',
    'fa': 'Persian',
    'ur': 'Urdu',
    'bn': 'Bengali',
    'ta': 'Tamil',
    'te': 'Telugu',
    'mr': 'Marathi',
    'gu': 'Gujarati',
    'kn': 'Kannada',
    'ml': 'Malayalam',
    'th': 'Thai',
    'vi': 'Vietnamese',
    'id': 'Indonesian',
    'ms': 'Malay',
    'tl': 'Tagalog',
    'sw': 'Swahili',
    'af': 'Afrikaans',
    'sq': 'Albanian',
    'hy': 'Armenian',
    'az': 'Azerbaijani',
    'eu': 'Basque',
    'be': 'Belarusian',
    'bs': 'Bosnian',
    'ca': 'Catalan',
    'cy': 'Welsh',
    'eo': 'Esperanto',
    'gl': 'Galician',
    'ka': 'Georgian',
    'ht': 'Haitian Creole',
    'ha': 'Hausa',
    'haw': 'Hawaiian',
    'iw': 'Hebrew',  # альтернативный код для иврита
    'hmn': 'Hmong',
    'ig': 'Igbo',
    'ga': 'Irish',
    'jw': 'Javanese',
    'km': 'Khmer',
    'lo': 'Lao',
    'la': 'Latin',
    'lb': 'Luxembourgish',
    'mg': 'Malagasy',
    'mt': 'Maltese',
    'mi': 'Maori',
    'mn': 'Mongolian',
    'ne': 'Nepali',
    'ny': 'Chichewa',
    'ps': 'Pashto',
    'pa': 'Punjabi',
    'sm': 'Samoan',
    'gd': 'Scottish Gaelic',
    'st': 'Sesotho',
    'sn': 'Shona',
    'sd': 'Sindhi',
    'si': 'Sinhala',
    'so': 'Somali',
    'su': 'Sundanese',
    'tg': 'Tajik',
    'tt': 'Tatar',
    'ti': 'Tigrinya',
    'to': 'Tongan',
    'tk': 'Turkmen',
    'ug': 'Uyghur',
    'uz': 'Uzbek',
    'xh': 'Xhosa',
    'yi': 'Yiddish',
    'yo': 'Yoruba',
    'zu': 'Zulu',
    'unknown': 'Unknown'
}

# Тестовые данные для проверки точности
TEST_DATASET = [
    {"text": "The quick brown fox jumps over the lazy dog", "expected": "en"},
    {"text": "Быстрая коричневая лиса прыгает через ленивую собаку", "expected": "ru"},
    {"text": "Le renard brun rapide saute par-dessus le chien paresseux", "expected": "fr"},
    {"text": "El rápido zorro marrón salta sobre el perro perezoso", "expected": "es"},
    {"text": "Der schnelle braune Fuchs springt über den faulen Hund", "expected": "de"}
]